### PR TITLE
add support for Surface Pro 3

### PR DESCRIPTION
**Pull request by wiccan2**

### CODE REVIEW

**Review by qzed — APPROVED** [review]
Thanks!

**Comment by qzed** [comment]
You should also submit this upstream at https://github.com/linuxwacom/libwacom. The Surface Pro 3 touchscreen should work out of the box with pretty much all current kernels.

**Comment by wiccan2** [comment]
I don't seem to be able to see the surface-pro3 file in the repo despite you having merged it. Has it been removed on a latter commit for some reason?

**Comment by qzed** [comment]
Huh, yeah seems like this has been dropped by accident somehow. I'll re-add it for the next update (I'm somewhat busy right now so may take a bit).

**Comment by qzed** [comment]
Sorry for the delay, I've re-added the tablet data now and pushed some new releases.

**Pull request merged**
